services:

  backend:
      container_name: backend-physio
      build:
        context: ..
        dockerfile: ./docker/backend.Dockerfile
      tty: True
      volumes:
        - ../backend/:/code/
      ports:
        - "${PORT}:${PORT}"

  db:
    container_name: db-physio
    image: postgres:${POSTGRES_IMAGE_TAG}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres:

